INSERT INTO [User] ([email],[fio],[login],[password],[role]) VALUES(N'ty@gmail.com',N'ty Medvemede',N'tuesaw',N'7893424',N'Студент')
INSERT INTO [User] ([email],[fio],[login],[password],[role]) VALUES(N't1y@gmail.com',N'ty Medvemede1',N'tuesaw1',N'7893424',N'Студент')
INSERT INTO [User] ([email],[fio],[login],[password],[role]) VALUES(N't2y@gmail.com',N'ty Medvemede2',N'tuesaw2',N'7893424',N'Студент')
INSERT INTO [User] ([email],[fio],[login],[password],[role]) VALUES(N'teach@gmail.com',N'teach Me',N'tu',N'7893424',N'Преподователь')
INSERT INTO [User] ([email],[fio],[login],[password],[role]) VALUES(N'teach1@gmail.com',N'teach Me1',N'tu1',N'7893424',N'Преподователь')
INSERT INTO [User] ([email],[fio],[login],[password],[role]) VALUES(N'teach2@gmail.com',N'teach Me2',N'tu2',N'7893424',N'Преподователь')

INSERT INTO [Group] ([name]) VALUES (N'363')
INSERT INTO [Group] ([name]) VALUES (N'463')

INSERT INTO [UserGroup] ([group],[user]) VALUES(1,1)
INSERT INTO [UserGroup] ([group],[user]) VALUES(1,2)
INSERT INTO [UserGroup] ([group],[user]) VALUES(2,1)

INSERT INTO [Subject] ([name]) VALUES('ин-яз')
INSERT INTO [Subject] ([name]) VALUES('русский')
INSERT INTO [Subject] ([name]) VALUES('обж')
INSERT INTO [Subject] ([name]) VALUES('мдк 11.01 Хузы')
INSERT INTO [Subject] ([name]) VALUES('мдк 12.07 ВВВВВ')
INSERT INTO [Room] ([name]) VALUES (' 1127')
INSERT INTO [Room] ([name]) VALUES ('99 ggg')
INSERT INTO [Room] ([name]) VALUES ('ad')
INSERT INTO [Room] ([name]) VALUES ('made in havenb')
INSERT INTO [Room] ([name]) VALUES ('228')

INSERT INTO [Shedule] ([group],[user],[room],[day_of_week],[start_time],[end_time],[subject],[full_date]) VALUES(1,2,1, N'Понедельник','08:00:00', '09:30:00',1, '2025-01-08')
INSERT INTO [Shedule] ([group],[user],[room],[day_of_week],[start_time],[end_time],[subject],[full_date]) VALUES(1,2,1, N'Понедельник','10:30:00', '11:30:00',2, '2025-01-08')
INSERT INTO [Shedule] ([group],[user],[room],[day_of_week],[start_time],[end_time],[subject],[full_date]) VALUES(1,2,1, N'Вторник','12:00:00', '13:30:00',2, '2025-01-09')
INSERT INTO [Shedule] ([group],[user],[room],[day_of_week],[start_time],[end_time],[subject],[full_date]) VALUES(1,2,1, N'Вторник','13:00:00', '22:30:00',1, '2025-01-09')
INSERT INTO [Shedule] ([group],[user],[room],[day_of_week],[start_time],[end_time],[subject],[full_date]) VALUES(1,2,1, N'Среда','14:20:00', '15:30:00',1, '2025-01-10')